### Variáveis
@baseUrl = http://localhost:3000
@adminToken = token_admin
@estudanteToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2FvQGVtYWlsLmNvbSIsInJvbGUiOiJlc3R1ZGFudGUiLCJpYXQiOjE3NjM3NjE1NDAsImV4cCI6MTc2Mzg0Nzk0MH0.fnhC9N8N5d7hdCfEkUrnJAZskbCQmYP6le-tawwAR3Y
@professorToken = token_professor


### ==============================================
### AUTENTICAÇÃO
### ==============================================

### Registrar Admin 1
POST {{baseUrl}}/auth/registro
Content-Type: application/json

{
"nome": "Admin Sistema",
"email": "admin@email.com",
"senha": "admin123",
"role": "admin"
}

### Registrar Estudante 1
POST {{baseUrl}}/auth/registro
Content-Type: application/json

{
"nome": "João Silva",
"email": "joao@email.com",
"senha": "senha123",
"role": "estudante"
}

### Registrar Professor 1
POST {{baseUrl}}/auth/registro
Content-Type: application/json

{
"nome": "Maria Santos",
"email": "maria@email.com",
"senha": "senha123",
"role": "professor"
}

### Login Admin 1
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
"email": "admin@email.com",
"senha": "admin123"
}

### Login Estudante 1
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
"email": "joao@email.com",
"senha": "senha123"
}

### Login Professor 1
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
"email": "maria@email.com",
"senha": "senha123"
}


### Logout Admin 1
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{adminToken}}


### ==============================================
### ESTUDANTE 1
### ==============================================

POST {{baseUrl}}/posts
Authorization: Bearer {{estudanteToken}}
Content-Type: application/json

{
  "conteudo": "Este é o primeiro post do estudante João Silva."
}